apiVersion: 1

datasources:
  - name: Mimir
    uid: mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Mimir
      prometheusVersion: 2.9.0
      timeInterval: 15s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "(?:traceID|trace_id|traceId)=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: loki
        filterBySpanID: true
        filterByTraceID: true
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        tags:
          - service.name
      lokiSearch:
        datasourceUid: loki
