apiVersion: 1

policies:
  - orgId: 1
    receiver: siem-local-webhook
    group_by:
      - grafana_folder
      - alertname
      - severity
      - owner
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: siem-local-webhook
        object_matchers:
          - [severity, =, critical]
        group_wait: 10s
        group_interval: 2m
        repeat_interval: 30m
      - receiver: siem-local-webhook
        object_matchers:
          - [severity, =, high]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
      - receiver: siem-local-webhook
        object_matchers:
          - [severity, =, medium]
        group_wait: 1m
        group_interval: 10m
        repeat_interval: 4h
      - receiver: siem-local-webhook
        object_matchers:
          - [category, =, data-quality]
        group_wait: 5m
        group_interval: 15m
        repeat_interval: 8h
