apiVersion: 1

templates:
  - orgId: 1
    name: siem-alert-templates
    template: |
      {{ define "siem.alert_title" -}}
      [{{ .Status | toUpper }}] {{ .CommonLabels.severity }} {{ .CommonLabels.alertname }}
      {{- end }}

      {{ define "siem.alert_message" -}}
      {{ range .Alerts -}}
      Summary: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Owner: {{ .Labels.owner }}
      Category: {{ .Labels.category }}
      Runbook: {{ .Annotations.runbook_url }}
      False positives: {{ .Annotations.false_positive_notes }}
      {{ end -}}
      {{- end }}
